"""
Sweep reliability-aware temporal detector/tracker merge rules.

This script is intentionally post-hoc: it consumes detector and tracker COCO
prediction JSON files that were already generated by inference.  Merge decisions
do not use GT; GT is only used for evaluation during the sweep.

Reliability score:

    R_det = detector_score
            + detector_bias
            - temporal_weight * detector_temporal_jump

    R_trk = tracker_score
            + tracker_bias
            - distance_penalty * distance_to_seed
            - temporal_weight * tracker_temporal_jump

When both candidates pass thresholds, tracker is selected if
R_trk > R_det + margin.  The detector/tracker mask IoU is logged as an
agreement feature and can be used as an optional disagreement gate.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import numpy as np
from PIL import Image
from pycocotools import mask as mask_utils

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if _SCRIPT_DIR not in sys.path:
    sys.path.insert(0, _SCRIPT_DIR)

from batch_evaluate_utils import compute_dice, compute_iou, decode_rle_mask


ACDC_CATEGORY_ID_TO_NAME = {
    1: "right ventricle",
    2: "myocardium",
    3: "left ventricle",
}


def _default_test_dir() -> str:
    return "/home/gaoqi/dataset/using/acdc/processed/sam3_video_npz_coco_fullframes_100/test"


def _default_input_dir() -> str:
    return (
        "/home/gaoqi/sam3/gq_experiment/acdc/"
        "scribble_sam3_tracker_image_init_v1_oracle_diagnosis"
    )


def _default_output_dir() -> str:
    return (
        "/home/gaoqi/sam3/gq_experiment/acdc/"
        "scribble_sam3_tracker_image_init_v1_reliability_temporal_merge_sweep"
    )


def _float_list(value: str) -> List[float]:
    return [float(v.strip()) for v in value.split(",") if v.strip()]


def _load_json(path: str | Path):
    with open(path, "r") as f:
        return json.load(f)


def _category_name(category: dict) -> str:
    if "names" in category and isinstance(category["names"], list):
        return str(category["names"][0])
    return str(category.get("name", category["id"]))


def _mask_iou(mask_a: np.ndarray, mask_b: np.ndarray) -> float:
    union = np.logical_or(mask_a, mask_b).sum()
    if union == 0:
        return 1.0
    inter = np.logical_and(mask_a, mask_b).sum()
    return float(inter / union)


def _mask_to_coco_result(
    image_id: int,
    category_id: int,
    mask: np.ndarray,
    score: float,
) -> dict:
    mask_u8 = np.asfortranarray(mask.astype(np.uint8))
    rle = mask_utils.encode(mask_u8)
    if isinstance(rle["counts"], bytes):
        rle["counts"] = rle["counts"].decode("ascii")
    height, width = mask.shape
    return {
        "image_id": int(image_id),
        "category_id": int(category_id),
        "segmentation": rle,
        "score": float(score),
        "area": float(mask.sum() / max(1, height * width)),
        "bbox": [0.0, 0.0, 0.0, 0.0],
    }


def _resize_mask(mask: np.ndarray, height: int, width: int) -> np.ndarray:
    if mask.shape == (height, width):
        return mask.astype(bool)
    return (
        np.array(
            Image.fromarray(mask.astype(np.uint8) * 255).resize(
                (width, height), Image.NEAREST
            )
        )
        > 0
    )


def _build_prediction_index(
    predictions: List[dict], images_by_id: Dict[int, dict]
) -> Dict[Tuple[int, int], dict]:
    pred_index = {}
    for pred in predictions:
        image_id = int(pred["image_id"])
        category_id = int(pred["category_id"])
        key = (image_id, category_id)
        score = float(pred.get("score", 0.0))
        prev = pred_index.get(key)
        if prev is not None and score <= float(prev["score"]):
            continue
        image_info = images_by_id[image_id]
        height = int(image_info["height"])
        width = int(image_info["width"])
        mask = decode_rle_mask(pred["segmentation"], height, width).astype(bool)
        mask = _resize_mask(mask, height, width)
        pred_index[key] = {
            "mask": mask,
            "score": score,
            "area_px": int(mask.sum()),
            "area_ratio": float(mask.sum() / max(1, height * width)),
        }
    return pred_index


def _build_gt_index(frame_coco: dict) -> Dict[Tuple[int, int], dict]:
    return {
        (int(ann["image_id"]), int(ann["category_id"])): ann
        for ann in frame_coco.get("annotations", [])
    }


def _decode_gt_mask(
    gt_index: Dict[Tuple[int, int], dict],
    image_id: int,
    category_id: int,
    height: int,
    width: int,
) -> np.ndarray:
    ann = gt_index.get((int(image_id), int(category_id)))
    if ann is None:
        return np.zeros((height, width), dtype=bool)
    mask = decode_rle_mask(ann["segmentation"], height, width)
    return _resize_mask(mask, height, width)


def _empty_pred(height: int, width: int) -> dict:
    return {
        "mask": np.zeros((height, width), dtype=bool),
        "score": 0.0,
        "area_px": 0,
        "area_ratio": 0.0,
    }


def _build_seed_distance_map(seed_report_path: Optional[str]) -> dict:
    if not seed_report_path or not os.path.isfile(seed_report_path):
        return {}
    report = _load_json(seed_report_path)
    seed_map = {}
    for volume, cats in report.items():
        for category_id, info in cats.items():
            frames = [
                int(item["frame_idx"])
                for item in info.get("conditioning_frames", [])
                if "frame_idx" in item
            ]
            seed_map[(volume, int(category_id))] = frames
    return seed_map


def _distance_to_seed(frame_idx: int, seed_frames: List[int]) -> int:
    if not seed_frames:
        return 10**6
    return int(min(abs(int(frame_idx) - int(seed)) for seed in seed_frames))


def _build_samples(
    *,
    frame_coco: dict,
    detector_predictions: List[dict],
    tracker_predictions: List[dict],
    seed_report_path: Optional[str],
) -> List[dict]:
    images_by_id = {int(img["id"]): img for img in frame_coco["images"]}
    categories = {
        int(cat["id"]): _category_name(cat) for cat in frame_coco["categories"]
    }
    gt_index = _build_gt_index(frame_coco)
    detector_index = _build_prediction_index(detector_predictions, images_by_id)
    tracker_index = _build_prediction_index(tracker_predictions, images_by_id)
    seed_map = _build_seed_distance_map(seed_report_path)

    images_by_volume = defaultdict(list)
    volume_name_by_id = {}
    for image_id, image_info in images_by_id.items():
        volume_id = int(image_info.get("video_id", image_id))
        slice_idx = int(image_info.get("original_slice_idx", image_info.get("frame_idx", 0)))
        file_name = os.path.basename(image_info["file_name"])
        volume_name = os.path.splitext(file_name)[0]
        volume_name_by_id[volume_id] = volume_name
        images_by_volume[volume_id].append((slice_idx, image_id))

    samples = []
    for volume_id, items in images_by_volume.items():
        volume_name = volume_name_by_id[volume_id]
        for slice_idx, image_id in sorted(items):
            image_info = images_by_id[image_id]
            height = int(image_info["height"])
            width = int(image_info["width"])
            frame_idx = int(image_info.get("frame_idx", slice_idx))
            for category_id, class_name in categories.items():
                detector = detector_index.get((image_id, category_id), _empty_pred(height, width))
                tracker = tracker_index.get((image_id, category_id), _empty_pred(height, width))
                gt_mask = _decode_gt_mask(
                    gt_index, image_id, category_id, height, width
                )
                detector_intersection = int(np.logical_and(detector["mask"], gt_mask).sum())
                tracker_intersection = int(np.logical_and(tracker["mask"], gt_mask).sum())
                gt_area_px = int(gt_mask.sum())
                seed_frames = seed_map.get((volume_name, category_id), [])
                samples.append(
                    {
                        "volume": volume_name,
                        "image_id": image_id,
                        "frame_idx": frame_idx,
                        "slice_idx": slice_idx,
                        "category_id": category_id,
                        "class_name": class_name,
                        "height": height,
                        "width": width,
                        "gt_mask": gt_mask,
                        "gt_area_px": gt_area_px,
                        "detector_mask": detector["mask"],
                        "detector_score": detector["score"],
                        "detector_area_px": detector["area_px"],
                        "detector_area_ratio": detector["area_ratio"],
                        "detector_intersection_px": detector_intersection,
                        "detector_union_px": int(
                            detector["area_px"] + gt_area_px - detector_intersection
                        ),
                        "tracker_mask": tracker["mask"],
                        "tracker_score": tracker["score"],
                        "tracker_area_px": tracker["area_px"],
                        "tracker_area_ratio": tracker["area_ratio"],
                        "tracker_intersection_px": tracker_intersection,
                        "tracker_union_px": int(
                            tracker["area_px"] + gt_area_px - tracker_intersection
                        ),
                        "detector_tracker_iou": _mask_iou(
                            detector["mask"], tracker["mask"]
                        ),
                        "seed_distance": _distance_to_seed(frame_idx, seed_frames),
                    }
                )
    _add_temporal_features(samples)
    return samples


def _local_temporal_jump(area_ratios: List[float], index: int) -> float:
    neighbors = []
    if index > 0:
        neighbors.append(area_ratios[index - 1])
    if index + 1 < len(area_ratios):
        neighbors.append(area_ratios[index + 1])
    if not neighbors:
        return 0.0
    ref = float(np.mean(neighbors))
    cur = float(area_ratios[index])
    denom = max(ref, cur, 1e-4)
    return float(abs(cur - ref) / denom)


def _add_temporal_features(samples: List[dict]) -> None:
    grouped = defaultdict(list)
    for sample in samples:
        grouped[(sample["volume"], sample["category_id"])].append(sample)

    for group in grouped.values():
        group.sort(key=lambda item: item["frame_idx"])
        det_areas = [float(item["detector_area_ratio"]) for item in group]
        trk_areas = [float(item["tracker_area_ratio"]) for item in group]
        for idx, item in enumerate(group):
            item["detector_temporal_jump"] = _local_temporal_jump(det_areas, idx)
            item["tracker_temporal_jump"] = _local_temporal_jump(trk_areas, idx)


def _candidate_reliability(sample: dict, config: dict) -> Tuple[float, float]:
    det_rel = (
        float(sample["detector_score"])
        + float(config["detector_bias"])
        - float(config["temporal_weight"]) * float(sample["detector_temporal_jump"])
    )
    trk_rel = (
        float(sample["tracker_score"])
        + float(config["tracker_bias"])
        - float(config["distance_penalty"]) * float(sample["seed_distance"])
        - float(config["temporal_weight"]) * float(sample["tracker_temporal_jump"])
    )
    return det_rel, trk_rel


def _choose_candidate(sample: dict, config: dict) -> Tuple[str, np.ndarray, float]:
    det_ok = (
        int(sample["detector_area_px"]) > 0
        and float(sample["detector_score"]) >= float(config["detector_threshold"])
    )
    trk_ok = (
        int(sample["tracker_area_px"]) > 0
        and float(sample["tracker_score"]) >= float(config["tracker_threshold"])
    )

    if det_ok and trk_ok:
        det_rel, trk_rel = _candidate_reliability(sample, config)
        disagreement = 1.0 - float(sample["detector_tracker_iou"])
        tracker_margin = float(config["margin"]) + float(config["disagreement_penalty"]) * disagreement
        if trk_rel > det_rel + tracker_margin:
            return "tracker", sample["tracker_mask"], sample["tracker_score"]
        return "detector", sample["detector_mask"], sample["detector_score"]
    if trk_ok:
        return "tracker", sample["tracker_mask"], sample["tracker_score"]
    if det_ok:
        return "detector", sample["detector_mask"], sample["detector_score"]
    return "none", np.zeros_like(sample["gt_mask"], dtype=bool), 0.0


def _evaluate_samples(samples: List[dict], config: dict) -> dict:
    grouped = defaultdict(
        lambda: {
            "intersection": 0,
            "pred_area": 0,
            "gt_area": 0,
            "union": 0,
        }
    )
    source_counts = Counter()
    agreement_by_source = defaultdict(list)
    temporal_by_source = defaultdict(list)

    for sample in samples:
        source, mask, _ = _choose_candidate(sample, config)
        source_counts[source] += 1
        agreement_by_source[source].append(float(sample["detector_tracker_iou"]))
        group_key = (sample["volume"], sample["category_id"], sample["class_name"])
        if source == "detector":
            temporal_by_source[source].append(float(sample["detector_temporal_jump"]))
            grouped[group_key]["intersection"] += int(sample["detector_intersection_px"])
            grouped[group_key]["pred_area"] += int(sample["detector_area_px"])
            grouped[group_key]["union"] += int(sample["detector_union_px"])
        elif source == "tracker":
            temporal_by_source[source].append(float(sample["tracker_temporal_jump"]))
            grouped[group_key]["intersection"] += int(sample["tracker_intersection_px"])
            grouped[group_key]["pred_area"] += int(sample["tracker_area_px"])
            grouped[group_key]["union"] += int(sample["tracker_union_px"])
        else:
            grouped[group_key]["union"] += int(sample["gt_area_px"])
        grouped[group_key]["gt_area"] += int(sample["gt_area_px"])

    per_class = defaultdict(lambda: {"dice": [], "iou": []})
    for (_, _, class_name), stats in grouped.items():
        denom = int(stats["pred_area"] + stats["gt_area"])
        if denom == 0:
            dice = 1.0
        else:
            dice = float(2.0 * stats["intersection"] / denom)
        if int(stats["union"]) == 0:
            iou = 1.0
        else:
            iou = float(stats["intersection"] / stats["union"])
        per_class[class_name]["dice"].append(dice)
        per_class[class_name]["iou"].append(iou)

    class_rows = {}
    dice_means = []
    iou_means = []
    for class_name, values in per_class.items():
        dice_values = np.array(values["dice"], dtype=np.float32)
        iou_values = np.array(values["iou"], dtype=np.float32)
        class_rows[class_name] = {
            "dice_mean": float(dice_values.mean()),
            "dice_std": float(dice_values.std()),
            "iou_mean": float(iou_values.mean()),
            "iou_std": float(iou_values.std()),
        }
        dice_means.append(class_rows[class_name]["dice_mean"])
        iou_means.append(class_rows[class_name]["iou_mean"])

    return {
        "overall_dice": float(np.mean(dice_means)),
        "overall_iou": float(np.mean(iou_means)),
        "source_counts": dict(source_counts),
        "per_class": class_rows,
        "mean_agreement_by_source": {
            key: float(np.mean(value)) for key, value in agreement_by_source.items() if value
        },
        "mean_temporal_jump_by_source": {
            key: float(np.mean(value)) for key, value in temporal_by_source.items() if value
        },
    }


def _write_predictions(samples: List[dict], config: dict, path: Path) -> None:
    predictions = []
    for sample in samples:
        source, mask, score = _choose_candidate(sample, config)
        if source == "none" or not mask.any():
            continue
        predictions.append(
            _mask_to_coco_result(
                image_id=int(sample["image_id"]),
                category_id=int(sample["category_id"]),
                mask=mask,
                score=float(score),
            )
        )
    predictions.sort(key=lambda item: (item["image_id"], item["category_id"]))
    with open(path, "w") as f:
        json.dump(predictions, f)


def _iter_configs(args) -> Iterable[dict]:
    for detector_threshold in _float_list(args.detector_thresholds):
        for tracker_threshold in _float_list(args.tracker_thresholds):
            for detector_bias in _float_list(args.detector_biases):
                for tracker_bias in _float_list(args.tracker_biases):
                    for temporal_weight in _float_list(args.temporal_weights):
                        for distance_penalty in _float_list(args.distance_penalties):
                            for disagreement_penalty in _float_list(args.disagreement_penalties):
                                for margin in _float_list(args.margins):
                                    yield {
                                        "detector_threshold": detector_threshold,
                                        "tracker_threshold": tracker_threshold,
                                        "detector_bias": detector_bias,
                                        "tracker_bias": tracker_bias,
                                        "temporal_weight": temporal_weight,
                                        "distance_penalty": distance_penalty,
                                        "disagreement_penalty": disagreement_penalty,
                                        "margin": margin,
                                    }


def parse_args():
    parser = argparse.ArgumentParser(
        description="Sweep reliability-aware temporal detector/tracker merge.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--test_dir", default=_default_test_dir())
    parser.add_argument("--frame_annotation_file", default="frame_annotations.coco.json")
    parser.add_argument(
        "--detector_predictions_json",
        default=os.path.join(_default_input_dir(), "detector_predictions_segm.json"),
    )
    parser.add_argument(
        "--tracker_predictions_json",
        default=os.path.join(_default_input_dir(), "tracker_predictions_segm.json"),
    )
    parser.add_argument(
        "--seed_report_json",
        default=os.path.join(_default_input_dir(), "seed_selection_report.json"),
    )
    parser.add_argument("--output_dir", default=_default_output_dir())
    parser.add_argument("--detector_thresholds", default="0.7,0.8")
    parser.add_argument("--tracker_thresholds", default="0.7,0.8")
    parser.add_argument("--detector_biases", default="0")
    parser.add_argument("--tracker_biases", default="0,0.02,0.05,0.08,0.1,0.15")
    parser.add_argument("--temporal_weights", default="0,0.02,0.05,0.1,0.2")
    parser.add_argument("--distance_penalties", default="0,0.005,0.01,0.02")
    parser.add_argument("--disagreement_penalties", default="0,0.02,0.05,0.1")
    parser.add_argument("--margins", default="-0.05,0,0.03,0.05,0.1")
    parser.add_argument(
        "--fixed_config_json",
        default=None,
        help="Use a previous best_config.json instead of selecting parameters.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    frame_coco = _load_json(Path(args.test_dir) / args.frame_annotation_file)
    detector_predictions = _load_json(args.detector_predictions_json)
    tracker_predictions = _load_json(args.tracker_predictions_json)

    samples = _build_samples(
        frame_coco=frame_coco,
        detector_predictions=detector_predictions,
        tracker_predictions=tracker_predictions,
        seed_report_path=args.seed_report_json,
    )

    if args.fixed_config_json:
        fixed = _load_json(args.fixed_config_json)
        config = fixed.get("config", fixed)
        metrics = _evaluate_samples(samples, config)
        best = {"config": config, "metrics": metrics}
        csv_path = None
        best_path = output_dir / "applied_config_results.json"
        with open(best_path, "w") as f:
            json.dump(best, f, indent=2)
    else:
        rows = []
        best = None
        for config in _iter_configs(args):
            metrics = _evaluate_samples(samples, config)
            row = {
                **config,
                "overall_dice": metrics["overall_dice"],
                "overall_iou": metrics["overall_iou"],
                "num_detector": metrics["source_counts"].get("detector", 0),
                "num_tracker": metrics["source_counts"].get("tracker", 0),
                "num_none": metrics["source_counts"].get("none", 0),
            }
            for class_name, values in metrics["per_class"].items():
                key = class_name.replace(" ", "_")
                row[f"{key}_dice"] = values["dice_mean"]
            rows.append(row)
            if best is None or metrics["overall_dice"] > best["metrics"]["overall_dice"]:
                best = {"config": config, "metrics": metrics, "row": row}

        rows.sort(key=lambda item: item["overall_dice"], reverse=True)
        csv_path = output_dir / "reliability_temporal_merge_sweep_results.csv"
        with open(csv_path, "w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
            writer.writeheader()
            writer.writerows(rows)

        assert best is not None
        best_path = output_dir / "best_config.json"
        with open(best_path, "w") as f:
            json.dump(best, f, indent=2)

    pred_path = output_dir / "best_reliability_temporal_merge_predictions_segm.json"
    _write_predictions(samples, best["config"], pred_path)

    print(f"Loaded samples: {len(samples)}")
    print(f"Best config: {best['config']}")
    print(f"Best overall Dice: {best['metrics']['overall_dice']:.6f}")
    print(f"Best source counts: {best['metrics']['source_counts']}")
    if csv_path is not None:
        print(f"Wrote: {csv_path}")
    print(f"Wrote: {best_path}")
    print(f"Wrote: {pred_path}")


if __name__ == "__main__":
    main()
