# @package _global_
defaults:
  - scribble_video_lora_100_context_v1
  - _self_

paths:
  experiment_log_dir: /home/gaoqi/sam3/gq_experiment/acdc/scribble_video_lora_100_context_v1_smoke

scratch:
  num_train_workers: 0
  num_val_workers: 0
  train_batch_size: 1
  val_batch_size: 1
  max_data_epochs: 1

trainer:
  data:
    train:
      dataset:
        limit_ids: 2
    val:
      dataset:
        limit_ids: 1
  checkpoint:
    save_freq: 1
  logging:
    tensorboard_writer:
      _target_: sam3.train.utils.logger.make_tensorboard_logger
      log_dir: ${launcher.experiment_log_dir}/tensorboard
      flush_secs: 120
      should_log: true
    wandb_writer: null
    log_dir: ${launcher.experiment_log_dir}/logs/acdc_scribble_video_lora_100_context_v1_smoke
    log_freq: 1

launcher:
  gpus_per_node: 1
